import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KFU Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="luxury">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-[#241400] bg-[#FFFAF5] `}
      >
        <nav className="flex justify-between px-24 py-6">
          <a href="/">
            <img
              src="logo.png"
              alt="logo"
              className="w-[150px] h-[40px] object-cover"
            />
          </a>
          <input
            type="text"
            placeholder="search"
            className="input text-white input-sm rounded-full"
          />
          <a className="btn rounded-full" href="/login">
            logout
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
